### PR TITLE
Continuous scroll syncronization

### PR DESCRIPTION
**Pull request by Galadirith**
WIP towards #9 and related #133, #152, #177. This has also been requested in atom/markdown-preview#24.

### CODE REVIEW

**Comment by Galadirith** [comment]
@mangecoeur @chaserhkj @KazWolfe @NobbZ @OJFord Thanks so much for all your requests and efforts towards implementing this feature.

A week ago I said I didn't have enough time. However a restless Friday evening and train up to a conference and I've managed to hack something together. I am very excited about this and I hope it will live up to all your expectations.

If you are able to please checkout this branch, and give it a go locally. I would really value all your opinions. I'm not sure exactly when this will be published, however the core logic is there, just bug fixes and tests to add.

Thanks everyone :D

**Comment by pdonias** [comment]
Hi!

I was just wondering if this will ever be released. This looks like a great enhancement! :)

Thanks!

**Comment by NobbZ** [comment]
Well, considering #188 it probably won't be released ever.

**Comment by pdonias** [comment]
Indeed. Thanks.

**Pull request closed without merging**
