### PR TITLE
Electron clipboard

### LINKED ISSUE #418: Copy to clipboard inserts editor styling and fonts
When I copy from the preview pane to the clipboard using "Copy as HTML" I would expect sparse output, with lean HTML. Instead, this is what I get:

```
<p style="box-sizing: border-box; margin: 0px 0px 15px; line-height: 1.6; color: rgb(60, 173, 215); font-family: ".SFNSText-Regular", "SF UI Text", "Lucida Grande", "Segoe UI", Ubuntu, Cantarell, sans-serif; font-size: 14.4px; font-variant-ligatures: normal; orphans: 2; widows: 2; background-color: rgb(14, 21, 27);">
My content here. <em style="box-sizing: border-box;">Emphasized.</em>
</p>
```
This is the output I would expect:

```
<p>
My content here. <em>Emphasized.</em>
</p>
```

Could there be an option for this? It seems that most people wouldn't want all that formatting, but some might.

I plan to have a crack at solving this. Is the output of styles a bug, or expected behavior? Is the addition of an option an acceptable solution, or not?

### PR DESCRIPTION
**Pull request by lierdakil**
- [X] I have looked over the [contribution guide](https://github.com/atom-community/markdown-preview-plus/blob/master/CONTRIBUTING.md), which contains some crucial technical information.

Use Electron clipboard interface directly; write rich HTML in addition to plain text if enabled.

Closes #418

### CODE REVIEW

**Comment by glassdimly** [comment]
Quick comment. You say "Copy rich text to clipboard in addition to raw HTML when using copy html commands". 

Using a clipboard history, which I do, this would be fine. But many people don't use a clipboard history and would only be able to paste the final object posted to the clipboard.

**Comment by glassdimly** [comment]
Oh I see, it's actually either/or. IMHO a separate menu item would be better than a config option, but this works just fine for me.

**Comment by lierdakil** [comment]
> Using a clipboard history, which I do, this would be fine. But many people don't use a clipboard history and would only be able to paste the final object posted to the clipboard.

The clipboard can contain multiple objects with different MIME types *simultaneously*. If a receiver can accept rich text, it will; but if it can't it'll fall back to plaintext. Does that make sense?

**Comment by lierdakil** [comment]
mpp-rich-clipboard-2
For example, notice how rich text is pasted in libreoffice, but raw HTML is pasted in Atom.

**Comment by glassdimly** [comment]
Ah yes, that's why calling `writeHTML` directly would be wrong. Cool, thanks.

**Pull request merged**
